USE db_kas_kelas;

INSERT INTO siswa (nama, nomor_absen) VALUES
('Ahmad Fauzi', 1),
('Siti Nurhaliza', 2),
('Budi Santoso', 3),
('Dewi Lestari', 4),
('Rudi Hermawan', 5),
('Rina Marlina', 6),
('Adi Saputra', 7),
('Fitri Handayani', 8),
('Dani Ramadhan', 9),
('Ani Rahmawati', 10),
('Fajar Nugroho', 11),
('Mega Puspita', 12),
('Gilang Pratama', 13),
('Indah Permata Sari', 14),
('Hendra Gunawan', 15),
('Nurul Aisyah', 16),
('Irfan Hakim', 17),
('Wulan Suciati', 18),
('Joko Susilo', 19),
('Yuni Astuti', 20),
('Rizky Firmansyah', 21),
('Dian Permata', 22),
('Dimas Ardiansyah', 23),
('Ratna Sari Dewi', 24),
('Eko Prasetyo', 25),
('Maya Anggraini', 26),
('Arif Hidayat', 27),
('Lilis Sulistiani', 28),
('Bayu Aji Prakoso', 29),
('Cici Fatimah', 30);
